"""add_resume_columns

Revision ID: 327ade8e5ce3
Revises: 8ddac22a2eda
Create Date: 2026-01-25 18:40:40.034645

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "327ade8e5ce3"
down_revision: Union[str, Sequence[str], None] = "8ddac22a2eda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###

    # Keeping only relevant column additions
    op.add_column("resumes", sa.Column("raw_resume_text", sa.Text(), nullable=True))
    op.add_column(
        "resumes", sa.Column("tailored_content_json", sa.Text(), nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("tailored_resume_yaml", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "tailored_resume_yaml")
    op.drop_column("resumes", "tailored_content_json")
    op.drop_column("resumes", "raw_resume_text")
    op.create_table(
        "events",
        sa.Column("id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "app_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "session_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "invocation_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "author", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("actions", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "long_running_tool_ids_json", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("branch", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "grounding_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "custom_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "usage_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "citation_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("partial", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("turn_complete", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "error_code", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "error_message", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column("interrupted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "input_transcription",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "output_transcription",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["app_name", "user_id", "session_id"],
            ["sessions.app_name", "sessions.user_id", "sessions.id"],
            name=op.f("events_app_name_user_id_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", "app_name", "user_id", "session_id", name=op.f("events_pkey")
        ),
    )
    op.create_table(
        "sessions",
        sa.Column(
            "app_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "create_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "update_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "app_name", "user_id", "id", name=op.f("sessions_pkey")
        ),
    )
    op.create_table(
        "user_states",
        sa.Column(
            "app_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "update_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("app_name", "user_id", name=op.f("user_states_pkey")),
    )
    op.create_table(
        "app_states",
        sa.Column(
            "app_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "update_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("app_name", name=op.f("app_states_pkey")),
    )
    # ### end Alembic commands ###
