"""cleanup_resume_columns

Revision ID: 5029d9640ed6
Revises: 327ade8e5ce3
Create Date: 2026-01-26 09:24:00.355366

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5029d9640ed6"
down_revision: Union[str, Sequence[str], None] = "327ade8e5ce3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "file_path")
    op.drop_column("resumes", "generation_prompt_used")
    op.drop_column("resumes", "position_title")
    op.drop_column("resumes", "generated_content")
    op.drop_column("resumes", "company_name")
    op.drop_column("resumes", "error_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column("generated_content", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "position_title", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "generation_prompt_used", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
